# Generated by Django 3.2.19 on 2023-09-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sebby', '0004_auto_20230903_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passanger', to='sebby.Flight')),
            ],
        ),
    ]
